# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from twins.state.v1 import state_pb2 as twins_dot_state_dot_v1_dot_state__pb2


class AssetStateServiceStub:
    """Streams calculated asset state for one immutable simulation run.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WatchAssetStates = channel.unary_stream(
                '/twins.state.v1.AssetStateService/WatchAssetStates',
                request_serializer=twins_dot_state_dot_v1_dot_state__pb2.WatchAssetStatesRequest.SerializeToString,
                response_deserializer=twins_dot_state_dot_v1_dot_state__pb2.WatchAssetStatesResponse.FromString,
                _registered_method=True)


class AssetStateServiceServicer:
    """Streams calculated asset state for one immutable simulation run.
    """

    def WatchAssetStates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WatchAssetStates': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAssetStates,
                    request_deserializer=twins_dot_state_dot_v1_dot_state__pb2.WatchAssetStatesRequest.FromString,
                    response_serializer=twins_dot_state_dot_v1_dot_state__pb2.WatchAssetStatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twins.state.v1.AssetStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twins.state.v1.AssetStateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssetStateService:
    """Streams calculated asset state for one immutable simulation run.
    """

    @staticmethod
    def WatchAssetStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/twins.state.v1.AssetStateService/WatchAssetStates',
            twins_dot_state_dot_v1_dot_state__pb2.WatchAssetStatesRequest.SerializeToString,
            twins_dot_state_dot_v1_dot_state__pb2.WatchAssetStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
