# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twins/state/v1/state.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'twins/state/v1/state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atwins/state/v1/state.proto\x12\x0etwins.state.v1\"t\n\x17WatchAssetStatesRequest\x12\x15\n\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n\tasset_ids\x18\x02 \x03(\tR\x08\x61ssetIds\x12%\n\x0e\x61\x66ter_sequence\x18\x03 \x01(\x04R\rafterSequence\"\xcd\x01\n\x15\x41ssetOperationalState\x12>\n\x04mode\x18\x01 \x01(\x0e\x32*.twins.state.v1.AssetOperationalState.ModeR\x04mode\"t\n\x04Mode\x12\x14\n\x10MODE_UNSPECIFIED\x10\x00\x12\x0c\n\x08MODE_OFF\x10\x01\x12\x11\n\rMODE_STARTING\x10\x02\x12\x10\n\x0cMODE_RUNNING\x10\x03\x12\x11\n\rMODE_STOPPING\x10\x04\x12\x10\n\x0cMODE_FAULTED\x10\x05\"\xa1\x02\n\x18WatchAssetStatesResponse\x12\x15\n\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n\x08sequence\x18\x02 \x01(\x04R\x08sequence\x12,\n\x12simulation_time_ns\x18\x03 \x01(\x03R\x10simulationTimeNs\x12\x19\n\x08\x61sset_id\x18\x04 \x01(\tR\x07\x61ssetId\x12\x33\n\x06origin\x18\x05 \x01(\x0e\x32\x1b.twins.state.v1.StateOriginR\x06origin\x12I\n\x0boperational\x18\n \x01(\x0b\x32%.twins.state.v1.AssetOperationalStateH\x00R\x0boperationalB\t\n\x07payload*s\n\x0bStateOrigin\x12\x1c\n\x18STATE_ORIGIN_UNSPECIFIED\x10\x00\x12\"\n\x1eSTATE_ORIGIN_SYNTHETIC_FIXTURE\x10\x01\x12\"\n\x1eSTATE_ORIGIN_SIMULATION_ENGINE\x10\x02\x32|\n\x11\x41ssetStateService\x12g\n\x10WatchAssetStates\x12\'.twins.state.v1.WatchAssetStatesRequest\x1a(.twins.state.v1.WatchAssetStatesResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twins.state.v1.state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATEORIGIN']._serialized_start=664
  _globals['_STATEORIGIN']._serialized_end=779
  _globals['_WATCHASSETSTATESREQUEST']._serialized_start=46
  _globals['_WATCHASSETSTATESREQUEST']._serialized_end=162
  _globals['_ASSETOPERATIONALSTATE']._serialized_start=165
  _globals['_ASSETOPERATIONALSTATE']._serialized_end=370
  _globals['_ASSETOPERATIONALSTATE_MODE']._serialized_start=254
  _globals['_ASSETOPERATIONALSTATE_MODE']._serialized_end=370
  _globals['_WATCHASSETSTATESRESPONSE']._serialized_start=373
  _globals['_WATCHASSETSTATESRESPONSE']._serialized_end=662
  _globals['_ASSETSTATESERVICE']._serialized_start=781
  _globals['_ASSETSTATESERVICE']._serialized_end=905
# @@protoc_insertion_point(module_scope)
